# Generated by Django 3.0.6 on 2020-11-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaires',
            name='Qs_Title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='Qs_Name',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
