# Generated by Django 3.0.6 on 2020-11-17 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Questionnaire', '0002_auto_20201115_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Share_Date', models.DateTimeField(auto_now=True)),
                ('Questionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Questionnaires')),
                ('UserName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qs_Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shares_Num', models.IntegerField(default=0)),
                ('Questionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Questionnaires')),
            ],
        ),
    ]
