# Generated by Django 3.0.6 on 2020-11-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0003_qs_shares_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaires',
            name='Qs_Dcrb',
            field=models.CharField(default='No Describtion', max_length=320),
        ),
    ]
