# Generated by Django 3.0.6 on 2020-12-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0004_questionnaires_qs_dcrb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaires',
            name='Qs_Name',
            field=models.CharField(max_length=160, null=True, unique=True),
        ),
    ]
