# Generated by Django 3.0.6 on 2020-12-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0005_auto_20201202_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qs_shares',
            name='id',
        ),
        migrations.AlterField(
            model_name='qs_shares',
            name='Questionnaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Questionnaire.Questionnaires'),
        ),
        migrations.AlterField(
            model_name='shares',
            name='Questionnaire',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Questionnaires'),
        ),
    ]
