# Generated by Django 3.0.6 on 2020-12-02 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0006_auto_20201202_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='Questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Questionnaires'),
        ),
    ]
