# Generated by Django 3.0.6 on 2020-11-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='Questionnais',
            new_name='Questionnairs',
        ),
    ]
