# Generated by Django 3.0.6 on 2020-12-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_contacts_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='UserName',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
