# Generated by Django 3.0.6 on 2020-11-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='Birthdate',
            field=models.DateField(null=True),
        ),
    ]
