# Generated by Django 3.0.6 on 2020-11-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_profiles_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='Qu_Shares',
            field=models.IntegerField(default=0, max_length=7),
        ),
        migrations.AddField(
            model_name='profiles',
            name='Questionnais',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
