# Generated by Django 3.0.6 on 2020-11-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_auto_20201113_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='Qu_Shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='Questionnais',
            field=models.IntegerField(default=0),
        ),
    ]
