# Generated by Django 3.0.6 on 2020-11-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_auto_20201115_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='Qu_Shares',
            new_name='Qs_Shares',
        ),
    ]
