# Generated by Django 3.0.6 on 2020-11-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_auto_20201117_1918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
